plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

application {
    mainClass = 'App'
}

javafx {
    version = '26'
    modules = ['javafx.controls', 'javafx.fxml']
}
